# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

# when using the default proxy server port
local_backend: true


media_folder: "assets/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Meta Description", name: "description", widget: "text", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Show Author Profile", name: "author_profile", widget: "boolean", default: true, required: true}
      - {label: "Show Share Buttons", name: "share", widget: "boolean", default: true, required: true}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "_pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Meta Description", name: "description", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Show Author Profile", name: "author_profile", widget: "boolean", default: true, required: true}
      - {label: "Show Share Buttons", name: "share", widget: "boolean", default: true, required: true}
  #resources
  - name: "resources"
    label: "Resources"
    folder: "_resources"
    sort: "title:asc"
    create: true
    slug: "resources/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Meta Description", name: "mdescription", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Show Author Profile", name: "author_profile", widget: "boolean", default: true, required: true}
      - {label: "Show Share Buttons", name: "share", widget: "boolean", default: true, required: true}
  #resources
  - name: "research"
    label: "Research"
    folder: "_research"
    sort: "title:asc"
    create: true
    slug: "research/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "description", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Show Author Profile", name: "author_profile", widget: "boolean", default: true, required: true}
      - {label: "Show Share Buttons", name: "share", widget: "boolean", default: true, required: true}
  #Others
  - name: others
    label: Others
    editor:
      preview: false
    files:
      - file: _data/navigation.yml
        label: Main Menus
        name: main_menus
        fields:
          - label: Main menus
            name: main_menus
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: "Path (example: /path/)", name: url, widget: string}
      - file: _data/settings.yml
        label: Settings
        name: settings
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      #author information
      - file: _data/author.yml
        label: Author Information
        name: author_information
        fields:
          - {label: "Full Name", name: "full_name", widget: "string", default: "Dr. Firoj Alam"}   
          - {label: "Nickname (Show on header)", name: "nickname", widget: "string", default: "Dr. Firoj Alam"}      
          - {label: "Avatar", name: "avatar", widget: "image", choose_url: false, default: "/assets/uploads/profile.png"}
          - {label: "Bio", name: "bio", widget: "string", default: "Postdoctoral Researcher Qatar Computing Research Institute"}  
          - {label: "Location", name: "location", widget: "string", default: ""}  
          - {label: "Employer", name: "employer", widget: "string", default: ""}  
          - {label: "Pubmed (full url)", name: "pubmed", widget: "string", default: ""}  
          - {label: "Googlescholar (full url)", name: "googlescholar", widget: "string", default: ""}  
          - {label: "Email", name: "email", widget: "string", default: ""}  
          - {label: "Researchgate (full url)", name: "researchgate", widget: "string", default: ""}  
          - {label: "Uri", name: "uri", widget: "string", default: ""}  
          - {label: "Bitbucket", name: "bitbucket", widget: "string", default: ""}  
          - {label: "Codepen", name: "codepen", widget: "string", default: ""}  
          - {label: "Dribbble", name: "dribbble", widget: "string", default: ""}  
          - {label: "Flickr", name: "flickr", widget: "string", default: ""}  
          - {label: "Facebook", name: "facebook", widget: "string", default: ""}  
          - {label: "Foursquare", name: "foursquare", widget: "string", default: ""}  
          - {label: "Github", name: "github", widget: "string", default: ""}  
          - {label: "Google_plus", name: "google_plus", widget: "string", default: ""}  
          - {label: "Keybase", name: "keybase", widget: "string", default: ""}  
          - {label: "Instagram", name: "instagram", widget: "string", default: ""}  
          - {label: "Impactstory (Full url)", name: "impactstory", widget: "string", default: ""}  
          - {label: "Lastfm", name: "lastfm", widget: "string", default: ""}  
          - {label: "Linkedin", name: "linkedin", widget: "string", default: ""}  
          - {label: "Orcid", name: "orcid", widget: "string", default: ""}  
          - {label: "Pinterest", name: "pinterest", widget: "string", default: ""}  
          - {label: "Soundcloud", name: "soundcloud", widget: "string", default: ""}  
          - {label: "Stackoverflow (Full)", name: "stackoverflow", widget: "string", default: ""}  
          - {label: "Steam", name: "steam", widget: "string", default: ""}  
          - {label: "Tumblr", name: "tumblr", widget: "string", default: ""}  
          - {label: "Twitter", name: "twitter", widget: "string", default: ""}  
          - {label: "Vine", name: "vine", widget: "string", default: ""}  
          - {label: "Youtube", name: "youtube", widget: "string", default: ""}  
          - {label: "Wikipedia", name: "wikipedia", widget: "string", default: ""}  
          - {label: "Banglanlp (Full url)", name: "banglanlp", widget: "string", default: ""}  
        
          
  
