# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

# when using the default proxy server port
local_backend: true

display_url: https://affectionate-jennings-c95921.netlify.app

media_folder: "assets/uploads" # Folder where user uploaded files should go

#publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          tagname: "h1",
          required: true,
        }
      - {
          label: "Meta Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Show Author Profile",
          name: "author_profile",
          widget: "boolean",
          default: true,
          required: true,
        }
      - {
          label: "Show Share Buttons",
          name: "share",
          widget: "boolean",
          default: true,
          required: true,
        }
    # PAGES
  - name: "page"
    label: "Page"
    folder: "_pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          tagname: "h1",
          required: true,
        }
      - {
          label: "Meta Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Show Author Profile",
          name: "author_profile",
          widget: "boolean",
          default: true,
          required: true,
        }
      - {
          label: "Show Share Buttons",
          name: "share",
          widget: "boolean",
          default: true,
          required: true,
        }
  #resources
  - name: "resources"
    label: "Resources"
    folder: "_resources"
    sort: "title:asc"
    create: true
    slug: "resources/{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          tagname: "h1",
          required: true,
        }
      - {
          label: "Meta Description",
          name: "mdescription",
          widget: "text",
          required: false,
        }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Show Author Profile",
          name: "author_profile",
          widget: "boolean",
          default: true,
          required: true,
        }
      - {
          label: "Show Share Buttons",
          name: "share",
          widget: "boolean",
          default: true,
          required: true,
        }
  #resources
  - name: "research"
    label: "Research"
    folder: "_research"
    sort: "title:asc"
    create: true
    slug: "research/{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Meta Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Show Author Profile",
          name: "author_profile",
          widget: "boolean",
          default: true,
          required: true,
        }
      - {
          label: "Show Share Buttons",
          name: "share",
          widget: "boolean",
          default: true,
          required: true,
        }
  #Others
  - name: others
    label: Others
    editor:
      preview: false
    files:
      - file: _data/navigation.yml
        label: Main Menus
        name: main-menus
        fields:
          - label: Main menus
            name: main-menus
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: "Path (example: /path/)", name: url, widget: string }
      - file: _data/settings.yml
        label: Settings
        name: settings
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Meta Description",
              name: "meta_description",
              widget: "string",
              required: false,
            }
      #author profile information
      - file: _data/profile.yml
        label: Profile
        name: my-profile
        fields:
          - {
              label: "Full Name",
              name: "full_name",
              widget: "string",
              default: "Dr. Firoj Alam",
            }
          - {
              label: "Avatar",
              name: "avatar",
              widget: "image",
              choose_url: false,
              default: "/assets/uploads/profile.png",
            }
          - {
              label: "Bio",
              name: "bio",
              widget: "string",
              default: "Postdoctoral Researcher Qatar Computing Research Institute",
            }
          - {
              label: "Location",
              name: "location",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Employer",
              name: "employer",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Pubmed (full url)",
              name: "pubmed",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Googlescholar (full url)",
              name: "googlescholar",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Email",
              name: "email",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Researchgate (full url)",
              name: "researchgate",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Uri",
              name: "uri",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Bitbucket",
              name: "bitbucket",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Codepen",
              name: "codepen",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Dribbble",
              name: "dribbble",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Flickr",
              name: "flickr",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Facebook",
              name: "facebook",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Foursquare",
              name: "foursquare",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Github",
              name: "github",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Google_plus",
              name: "google_plus",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Keybase",
              name: "keybase",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Instagram",
              name: "instagram",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Impactstory (Full url)",
              name: "impactstory",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Lastfm",
              name: "lastfm",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Linkedin",
              name: "linkedin",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Orcid",
              name: "orcid",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Pinterest",
              name: "pinterest",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Soundcloud",
              name: "soundcloud",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Stackoverflow (Full)",
              name: "stackoverflow",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Steam",
              name: "steam",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Tumblr",
              name: "tumblr",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Twitter",
              name: "twitter",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Vine",
              name: "vine",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Youtube",
              name: "youtube",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Wikipedia",
              name: "wikipedia",
              widget: "string",
              default: " ",
              required: false,
            }
          - {
              label: "Banglanlp (Full url)",
              name: "banglanlp",
              widget: "string",
              default: " ",
              required: false,
            }
